### ISSUE TITLE
No weekly overview at https://data.bibliometrics.lib.kth.se/kthcorpus/mods/index.html

### ISSUE THREAD

**Issue by awandahl** [KTH-Library/kthcorpus#167]
The overview over weekly MODS imports is missing this week. The GH action seems to have been executed though.

**Comment by mskyttner** [comment]
Now [available](https://data.bibliometrics.lib.kth.se/kthcorpus/mods/index.html), likely caused by an intermittent timeout glitch when listing the files.

**Comment by mskyttner** [comment]
Fixed by re-running the job.
