### ISSUE TITLE
FAILED: Generate MODS report #53: Scheduled

### ISSUE THREAD

**Issue by awandahl** [KTH-Library/kthcorpus#174]
MODS report for 2024-07-03--2024-07-10 failed. mods.qmd says

processing file: mods.qmd
  |............................                        |  53% [unnamed-chunk-4]`kthb/kthcorpus/pub.csv` -> `C:/Users/aw/AppData/Local/kthcorpus/kthcorpus/pub.csv`
Total: 0 B, Transferred: 173.66 MiB, Speed: 2.07 MiB/s
  |.................................................   |  93% [unnamed-chunk-7]Error in `read_xml.raw()`:
! StartTag: invalid element name [68]
Backtrace:
 1. kthcorpus:::create_diva_modscollection(my_mods_ar)
 3. xml2:::read_xml.character(collection)
 4. xml2:::read_xml.raw(...)

Quitting from lines 272-396 [unnamed-chunk-7] (mods.qmd)
                                                                                                            
Execution halted

**Comment by awandahl** [comment]
It would be nice to just spit out failing publications and make sure that the process is ending partly successful no matter what.

**Comment by awandahl** [comment]
And analyze why it's failing of course.

**Comment by mskyttner** [comment]
Investigating this now...
