### ISSUE TITLE
FAILED: Generate MODS report #54: Scheduled 

### ISSUE THREAD

**Issue by awandahl** [KTH-Library/kthcorpus#176]
This action failed too, but I managed to retrieve the metadata using RStudio and the quarto in /inst/markdown/report-mods.

**Comment by mskyttner** [comment]
Error message from the logs indicates perhaps that some inputs may have contained characters that clash with XML syntactic rules, and perhaps need to be wrapped in CDATA...

```
Error in `read_xml.raw()`:
! StartTag: invalid element name [68]
```

Will leave open as I cannot replicate presently.
