### ISSUE TITLE
Scopus > MODS: character "&" should be escaped?

### ISSUE THREAD

**Issue by awandahl** [KTH-Library/kthcorpus#42]
<affiliation>Department of Geography & Planning, School of Environmental Sciences, University of Liverpool, Liverpool, UK</affiliation>
I Guess "&" in affiliation names (and at other places) should be escaped, XML validator says "The entity name must immediately follow the '&' in the entity reference"

**Comment by mskyttner** [comment]
Hmmm... ok... either escape or could CDATA be used?

**Comment by awandahl** [comment]
CDATA is apparently better for all content in fields like this, i.e fields with random text that should be passed to MODS literally

**Comment by mskyttner** [comment]
Tried this on todays 91 articles and the xml validates for all of these now. Another question is if uploads to DiVA will work.

**Comment by mskyttner** [comment]
Thanks for spotting @awandahl !
