### ISSUE TITLE
Error in names(object) <- nm :    'names' attribute [10] must be the same length as the vector [8]

### ISSUE THREAD

**Issue by awandahl** [KTH-Library/kthcorpus#45]
Running example code from document mods_from_scopus.html throwing an error, I'm too much a neophyte to understand:

> my_mods <- my_sids |> scopus_mods_crawl(scopus = scopus, ko = ko)
Generating MODS parameters for 10 identifiers...
Failed to generate parameters for these ids: SCOPUS_ID:85147970587SCOPUS_ID:85147928526                     
Generating MODS based on parameters...
Error in names(object) <- nm : 
  'names' attribute [10] must be the same length as the vector [8]

**Comment by mskyttner** [comment]
Thanks for reporting! Reproduced.
