### ISSUE TITLE
MODS generation fails for some identifiers with sparse affiliation details and no abstracts

### ISSUE THREAD

**Issue by awandahl** [KTH-Library/kthcorpus#47]
> sids <- articles$`dc:identifier`
> my_sids <- sids |> head(200)
> my_mods <- my_sids |> scopus_mods_crawl(scopus = scopus, ko = ko)
Generating MODS parameters for 81 identifiers...
Failed to generate parameters for these ids:  SCOPUS_ID:85148093031  SCOPUS_ID:85148091482  SCOPUS_ID:85148079388  SCOPUS_ID:85148108363  SCOPUS_ID:85148053986
Generating MODS based on parameters...
Error in names(object) <- nm :
'names' attribute [81] must be the same length as the vector [76]

**Comment by mskyttner** [comment]
Reproduced.
