### ISSUE TITLE
KuraTHor Extern Swepub-control - change of links/labelling

### ISSUE THREAD

**Issue by nhamexy** [KTH-Library/kthcorpus#68]
The PID column in the Swepub checks goes to the wrong place. Suggestion: the PID column should be relabeled something like "Swepub_url" and go to https://swepub.kb.se/bib/swepub:oai:DiVA.org:kth-324493 where the last number is the PID.

**Comment by mskyttner** [comment]
@awandahl what do you think about the following format? A few rows:

|swepub_url                                                                                                                                                                                                                                                                                              |mods_url                                                                                                                                                                                                                                                                              |repository_url                                                                                                                                                                                            |record_id               |source | publication_year|publication_type |output_type                                                                                                                                                                                                                   |flag_class |flag_type |flag_code |validation_rule |value                                                                                                                                         |old_value           |new_value  |path                                                     |
|:-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|:-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|:---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|:-----------------------|:------|----------------:|:----------------|:-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|:----------|:---------|:---------|:---------------|:---------------------------------------------------------------------------------------------------------------------------------------------|:-------------------|:----------|:--------------------------------------------------------|
|<a href='https://swepub.kb.se/showrecord?q=onr:%22swepub:oai:DiVA.org:kth-324493%22&n=1&d=swepub&noredirect=true' target='_blank' rel='noopener noreferrer' title='https://swepub.kb.se/showrecord?q=onr:%22swepub:oai:DiVA.org:kth-324493%22&n=1&d=swepub&noredirect=true'>oai:DiVA.org:kth-324493</a> |<a href='https://bibliometri.swepub.kb.se/api/v1/process/publications/oai:DiVA.org:kth-324493/original' target='_blank' rel='noopener noreferrer' title='https://bibliometri.swepub.kb.se/api/v1/process/publications/oai:DiVA.org:kth-324493/original'>https://bibliometri.sw...</a> |<a href='http://urn.kb.se/resolve?urn=urn:nbn:se:kth:diva-324493' target='_blank' rel='noopener noreferrer' title='http://urn.kb.se/resolve?urn=urn:nbn:se:kth:diva-324493'>http://urn.kb.se/resol...</a> |oai:DiVA.org:kth-324493 |kth    |             2023|NA               |<a href='https://id.kb.se/term/swepub/output/publication/journal-article' target='_blank' rel='noopener noreferrer' title='https://id.kb.se/term/swepub/output/publication/journal-article'>https://id.kb.se/term/...</a>     |validation |ORCID     |span      |invalid         |<a href='https://orcid.org/0009-0002-1067-9697' target='_blank' rel='noopener noreferrer' title='0009-0002-1067-9697'>0009-0002-1067-9697</a> |NA                  |NA         |instanceOf.contribution.[0].agent.identifiedBy.[1].value |
|<a href='https://swepub.kb.se/showrecord?q=onr:%22swepub:oai:DiVA.org:kth-324493%22&n=1&d=swepub&noredirect=true' target='_blank' rel='noopener noreferrer' title='https://swepub.kb.se/showrecord?q=onr:%22swepub:oai:DiVA.org:kth-324493%22&n=1&d=swepub&noredirect=true'>oai:DiVA.org:kth-324493</a> |<a href='https://bibliometri.swepub.kb.se/api/v1/process/publications/oai:DiVA.org:kth-324493/original' target='_blank' rel='noopener noreferrer' title='https://bibliometri.swepub.kb.se/api/v1/process/publications/oai:DiVA.org:kth-324493/original'>https://bibliometri.sw...</a> |<a href='http://urn.kb.se/resolve?urn=urn:nbn:se:kth:diva-324493' target='_blank' rel='noopener noreferrer' title='http://urn.kb.se/resolve?urn=urn:nbn:se:kth:diva-324493'>http://urn.kb.se/resol...</a> |oai:DiVA.org:kth-324493 |kth    |             2023|NA               |<a href='https://id.kb.se/term/swepub/output/publication/journal-article' target='_blank' rel='noopener noreferrer' title='https://id.kb.se/term/swepub/output/publication/journal-article'>https://id.kb.se/term/...</a>     |enrichment |ORCID     |removed   |NA              |NA                                                                                                                                            |0009-0002-1067-9697 |[redacted] |instanceOf.contribution.[0].agent.identifiedBy.[1].value |
|<a href='https://swepub.kb.se/showrecord?q=onr:%22swepub:oai:DiVA.org:kth-324494%22&n=1&d=swepub&noredirect=true' target='_blank' rel='noopener noreferrer' title='https://swepub.kb.se/showrecord?q=onr:%22swepub:oai:DiVA.org:kth-324494%22&n=1&d=swepub&noredirect=true'>oai:DiVA.org:kth-324494</a> |<a href='https://bibliometri.swepub.kb.se/api/v1/process/publications/oai:DiVA.org:kth-324494/original' target='_blank' rel='noopener noreferrer' title='https://bibliometri.swepub.kb.se/api/v1/process/publications/oai:DiVA.org:kth-324494/original'>https://bibliometri.sw...</a> |<a href='http://urn.kb.se/resolve?urn=urn:nbn:se:kth:diva-324494' target='_blank' rel='noopener noreferrer' title='http://urn.kb.se/resolve?urn=urn:nbn:se:kth:diva-324494'>http://urn.kb.se/resol...</a> |oai:DiVA.org:kth-324494 |kth    |             2023|NA               |<a href='https://id.kb.se/term/swepub/output/publication/licentiate-thesis' target='_blank' rel='noopener noreferrer' title='https://id.kb.se/term/swepub/output/publication/licentiate-thesis'>https://id.kb.se/term/...</a> |validation |ORCID     |span      |invalid         |<a href='https://orcid.org/0009-0002-1067-9697' target='_blank' rel='noopener noreferrer' title='0009-0002-1067-9697'>0009-0002-1067-9697</a> |NA                  |NA         |instanceOf.contribution.[0].agent.identifiedBy.[1].value |
|<a href='https://swepub.kb.se/showrecord?q=onr:%22swepub:oai:DiVA.org:kth-324494%22&n=1&d=swepub&noredirect=true' target='_blank' rel='noopener noreferrer' title='https://swepub.kb.se/showrecord?q=onr:%22swepub:oai:DiVA.org:kth-324494%22&n=1&d=swepub&noredirect=true'>oai:DiVA.org:kth-324494</a> |<a href='https://bibliometri.swepub.kb.se/api/v1/process/publications/oai:DiVA.org:kth-324494/original' target='_blank' rel='noopener noreferrer' title='https://bibliometri.swepub.kb.se/api/v1/process/publications/oai:DiVA.org:kth-324494/original'>https://bibliometri.sw...</a> |<a href='http://urn.kb.se/resolve?urn=urn:nbn:se:kth:diva-324494' target='_blank' rel='noopener noreferrer' title='http://urn.kb.se/resolve?urn=urn:nbn:se:kth:diva-324494'>http://urn.kb.se/resol...</a> |oai:DiVA.org:kth-324494 |kth    |             2023|NA               |<a href='https://id.kb.se/term/swepub/output/publication/licentiate-thesis' target='_blank' rel='noopener noreferrer' title='https://id.kb.se/term/swepub/output/publication/licentiate-thesis'>https://id.kb.se/term/...</a> |enrichment |ORCID     |removed   |NA              |NA                                                                                                                                            |0009-0002-1067-9697 |[redacted] |instanceOf.contribution.[0].agent.identifiedBy.[1].value |
|<a href='https://swepub.kb.se/showrecord?q=onr:%22swepub:oai:DiVA.org:kth-324507%22&n=1&d=swepub&noredirect=true' target='_blank' rel='noopener noreferrer' title='https://swepub.kb.se/showrecord?q=onr:%22swepub:oai:DiVA.org:kth-324507%22&n=1&d=swepub&noredirect=true'>oai:DiVA.org:kth-324507</a> |<a href='https://bibliometri.swepub.kb.se/api/v1/process/publications/oai:DiVA.org:kth-324507/original' target='_blank' rel='noopener noreferrer' title='https://bibliometri.swepub.kb.se/api/v1/process/publications/oai:DiVA.org:kth-324507/original'>https://bibliometri.sw...</a> |<a href='http://urn.kb.se/resolve?urn=urn:nbn:se:kth:diva-324507' target='_blank' rel='noopener noreferrer' title='http://urn.kb.se/resolve?urn=urn:nbn:se:kth:diva-324507'>http://urn.kb.se/resol...</a> |oai:DiVA.org:kth-324507 |kth    |             2023|NA               |<a href='https://id.kb.se/term/swepub/output/publication/report' target='_blank' rel='noopener noreferrer' title='https://id.kb.se/term/swepub/output/publication/report'>https://id.kb.se/term/...</a>                       |validation |ORCID     |span      |invalid         |<a href='https://orcid.org/0009-0002-3431-4107' target='_blank' rel='noopener noreferrer' title='0009-0002-3431-4107'>0009-0002-3431-4107</a> |NA                  |NA         |instanceOf.contribution.[3].agent.identifiedBy.[1].value |
|<a href='https://swepub.kb.se/showrecord?q=onr:%22swepub:oai:DiVA.org:kth-324507%22&n=1&d=swepub&noredirect=true' target='_blank' rel='noopener noreferrer' title='https://swepub.kb.se/showrecord?q=onr:%22swepub:oai:DiVA.org:kth-324507%22&n=1&d=swepub&noredirect=true'>oai:DiVA.org:kth-324507</a> |<a href='https://bibliometri.swepub.kb.se/api/v1/process/publications/oai:DiVA.org:kth-324507/original' target='_blank' rel='noopener noreferrer' title='https://bibliometri.swepub.kb.se/api/v1/process/publications/oai:DiVA.org:kth-324507/original'>https://bibliometri.sw...</a> |<a href='http://urn.kb.se/resolve?urn=urn:nbn:se:kth:diva-324507' target='_blank' rel='noopener noreferrer' title='http://urn.kb.se/resolve?urn=urn:nbn:se:kth:diva-324507'>http://urn.kb.se/resol...</a> |oai:DiVA.org:kth-324507 |kth    |             2023|NA               |<a href='https://id.kb.se/term/swepub/output/publication/report' target='_blank' rel='noopener noreferrer' title='https://id.kb.se/term/swepub/output/publication/report'>https://id.kb.se/term/...</a>                       |enrichment |ORCID     |removed   |NA              |NA                                                                                                                                            |0009-0002-3431-4107 |[redacted] |instanceOf.contribution.[3].agent.identifiedBy.[1].value |
