### ISSUE TITLE
Fail when generating parameters for MODS 

### ISSUE THREAD

**Issue by awandahl** [KTH-Library/kthcorpus#75]
Revisiting the MODS generation today. Generation of parameters fail for 9 pubs out of 10. Code is up to date. Package rebuilt and loaded.

> library(kthcorpus)

Restarting R session...

> library(kthcorpus)
> devtools::load_all(".")
ℹ Loading kthcorpus
> scopus <- scopus_from_minio()
                                                                                                                                    
> ko <- kthid_orcid()
                                                                                                                                    
> articles <- scopus$publications |> filter(subtype == "cp")
> sids <- articles$`dc:identifier`
> my_sids <- sids |> head(10)
> my_mods <- my_sids |> scopus_mods_crawl(scopus = scopus, ko = ko)
Generating MODS parameters for 10 identifiers...
Failed to generate parameters for these ids:                                                                                        
 SCOPUS_ID:85159204362
 SCOPUS_ID:85159152232
 SCOPUS_ID:85159223902
 SCOPUS_ID:85159207729
 SCOPUS_ID:85159215013
 SCOPUS_ID:85159078582
 SCOPUS_ID:85159048585
 SCOPUS_ID:85159132088
 SCOPUS_ID:85159124691
Generating MODS based on parameters...
Failed to generate valid MODS xml for these ids: 
 SCOPUS_ID:85159204362
 SCOPUS_ID:85159152232
 SCOPUS_ID:85159223902
 SCOPUS_ID:85159207729
 SCOPUS_ID:85159215013
 SCOPUS_ID:85159078582
 SCOPUS_ID:85159048585
 SCOPUS_ID:85159132088
 SCOPUS_ID:85159124691
Returning 1 MODS invisibly
Warning message:
In scopus_mods_crawl(my_sids, scopus = scopus, ko = ko) :
  Failed conversion for these identifiers:
 SCOPUS_ID:85159204362
 SCOPUS_ID:85159152232
 SCOPUS_ID:85159223902
 SCOPUS_ID:85159207729
 SCOPUS_ID:85159215013
 SCOPUS_ID:85159078582
 SCOPUS_ID:85159048585
 SCOPUS_ID:85159132088
 SCOPUS_ID:85159124691

**Comment by mskyttner** [comment]
This is due to download_searchdb() expects "/tmp" to be available. It could/should be made platform independent and attempt to create the directory if it doesn't exist. Probably using package rappdirs.
