### ISSUE TITLE
DiVA-MODS: eissn:s are not rendered in the xml-records

### ISSUE THREAD

**Issue by awandahl** [KTH-Library/kthcorpus#81]
eissn isn't rendered in the xml. In diva_mods.R line 834 ff  I guess it should be enough to add a row like:

```
<identifier type="eissn">{pub_eissn}</identifier> 
```

to sort this out + maybe some more in scopus_mods.R and in whisker? I tried to change the code in two places myself, but it failed when running. Like this?
```
<relatedItem type="host">
    <titleInfo>
      <title>{pub_title}</title>
    </titleInfo>
    <identifier type="issn">{pub_issn}</identifier>
    <identifier type="eissn">{pub_eissn}</identifier>
    <part>
      <detail type="volume">........
```

**Comment by awandahl** [comment]
I may have solved this now myself. Apparently I committed to main, should have made a branch instead. Sorry!

**Comment by mskyttner** [comment]
Sounds good! You didn't push to github, so you can still create a new branch and push it, then we can make a PR and merge it.
