### ISSUE TITLE
MODS-generation: Failed to generate parameters for certain ids

### ISSUE THREAD

**Issue by awandahl** [KTH-Library/kthcorpus#93]
Date period was 2023-01-01--2023-02-28 and publication type conference papers.

Warning message:
In scopus_mods_crawl(sids = sids_cp, scopus = scopus, ko = kthid_orcid_lookup) :
  Failed conversion for these identifiers:
 SCOPUS_ID:85148497118
 SCOPUS_ID:85146304521

Date period was 2023-03-01--2023-04-30 and publication type conference papers.

Warning message:
In scopus_mods_crawl(sids = sids_cp, scopus = scopus, ko = kthid_orcid_lookup) :
  Failed conversion for these identifiers:
 SCOPUS_ID:85152489651

Date period was 2023-03-01--2023-04-30 and publication type other.

Warning message:
In scopus_mods_crawl(sids = sids_other, scopus = scopus, ko = kthid_orcid_lookup) :
  Failed conversion for these identifiers:
 SCOPUS_ID:85149933573
 SCOPUS_ID:85149912365
 SCOPUS_ID:85149505088
 SCOPUS_ID:85149564601

**Comment by mskyttner** [comment]
I added some logging which might give background as to why these ids were failing:

```
Found no conference event info for 2-s2.0-85148497118
Found no conference event info for 2-s2.0-85146304521
Found no conference event info for 2-s2.0-85152489651
Skipping extraction of conf info for sid 85149933573 due to aggregation type: Book Series, and pubtype: Book Chapter
Skipping extraction of conf info for sid 85149912365 due to aggregation type: Book Series, and pubtype: Book Chapter
Skipping extraction of conf info for sid 85149505088 due to aggregation type: Book, and pubtype: Book
Skipping extraction of conf info for sid 85149564601 due to aggregation type: Book, and pubtype: Book Chapter
```
