### ISSUE TITLE
MODS conference data parameter not picked up properly

### ISSUE THREAD

**Issue by awandahl** [KTH-Library/kthcorpus#97]
2-s2.0-85147324300  renders

2022 IEEE International Conference on Robotics and Biomimetics, ROBIO 2022, Jinghong, China, Dec -d 2022 - Dec -d 2022
After checking a few more records I realize that this issue actually goes for all of them... hmmm. We are talking "cp" and all time periods.

**Comment by mskyttner** [comment]
Hmmm.... I get:

```r
$ "2-s2.0-85147324300" |> 
   scopus_abstract_extended() |> 
   getElement("scopus_confinfo") |> 
   getElement("conf_details")

2022 IEEE International Conference on Robotics and Biomimetics, ROBIO 2022, Jinghong, China, Dec 9 2022 - Dec 5 2022
```

Looking further into this...

If you run that snippet, do you different output?

**Comment by mskyttner** [comment]
Maybe it is a locale setting or Windows specific issue? Can you try:

```r
> strftime(as.Date("2022-12-05"), "%b %-d %Y")
[1] "Dec 5 2022"

> locale()
<locale>
Numbers:  123,456.78
Formats:  %AD / %AT
Timezone: UTC
Encoding: UTF-8
<date_names>
Days:   Sunday (Sun), Monday (Mon), Tuesday (Tue), Wednesday (Wed), Thursday (Thu), Friday (Fri),
        Saturday (Sat)
Months: January (Jan), February (Feb), March (Mar), April (Apr), May (May), June (Jun), July (Jul),
        August (Aug), September (Sep), October (Oct), November (Nov), December (Dec)
AM/PM:  AM/PM
```

**Comment by mskyttner** [comment]
@Ealdwide confirms, output of `strftime(as.Date("2022-12-05"), "%b %-d %Y")` gives `dec -d 2022` on non-Linux platform.
